2024-01-30 16:09:14,263 INFO    MainThread:2042 [wandb_setup.py:_flush():76] Current SDK version is 0.15.5
2024-01-30 16:09:14,264 INFO    MainThread:2042 [wandb_setup.py:_flush():76] Configure stats pid to 2042
2024-01-30 16:09:14,264 INFO    MainThread:2042 [wandb_setup.py:_flush():76] Loading settings from /nethome/wmu30/.config/wandb/settings
2024-01-30 16:09:14,264 INFO    MainThread:2042 [wandb_setup.py:_flush():76] Loading settings from /mnt/284ac980-b350-4035-8e02-707f671ad89e/wmu30/googledrive-gui/wandb/settings
2024-01-30 16:09:14,264 INFO    MainThread:2042 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-01-30 16:09:14,264 INFO    MainThread:2042 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-01-30 16:09:14,264 INFO    MainThread:2042 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'design_baselines/diff_branin/classifier.py', 'program': 'design_baselines/diff_branin/classifier.py'}
2024-01-30 16:09:14,264 INFO    MainThread:2042 [wandb_init.py:_log_setup():507] Logging user logs to ./experiments/branin/new_classifier_ellipse_128/123_GMM3/wandb/run-20240130_160914-5caosgwi/logs/debug.log
2024-01-30 16:09:14,264 INFO    MainThread:2042 [wandb_init.py:_log_setup():508] Logging internal logs to ./experiments/branin/new_classifier_ellipse_128/123_GMM3/wandb/run-20240130_160914-5caosgwi/logs/debug-internal.log
2024-01-30 16:09:14,265 INFO    MainThread:2042 [wandb_init.py:init():547] calling init triggers
2024-01-30 16:09:14,265 INFO    MainThread:2042 [wandb_init.py:init():555] wandb.init called with sweep_config: {}
config: {}
2024-01-30 16:09:14,265 INFO    MainThread:2042 [wandb_init.py:init():596] starting backend
2024-01-30 16:09:14,265 INFO    MainThread:2042 [wandb_init.py:init():600] setting up manager
2024-01-30 16:09:14,270 INFO    MainThread:2042 [backend.py:_multiprocessing_setup():108] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-01-30 16:09:14,273 INFO    MainThread:2042 [wandb_init.py:init():606] backend started and connected
2024-01-30 16:09:14,277 INFO    MainThread:2042 [wandb_init.py:init():705] updated telemetry
2024-01-30 16:09:14,278 INFO    MainThread:2042 [wandb_init.py:init():738] communicating run to backend with 60.0 second timeout
2024-01-30 16:09:14,569 INFO    MainThread:2042 [wandb_run.py:_on_init():2173] communicating current version
2024-01-30 16:09:14,685 INFO    MainThread:2042 [wandb_run.py:_on_init():2182] got version response upgrade_message: "wandb version 0.16.2 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2024-01-30 16:09:14,685 INFO    MainThread:2042 [wandb_init.py:init():789] starting run threads in backend
2024-01-30 16:09:21,441 INFO    MainThread:2042 [wandb_run.py:_console_start():2152] atexit reg
2024-01-30 16:09:21,441 INFO    MainThread:2042 [wandb_run.py:_redirect():2007] redirect: SettingsConsole.WRAP_RAW
2024-01-30 16:09:21,442 INFO    MainThread:2042 [wandb_run.py:_redirect():2072] Wrapping output streams.
2024-01-30 16:09:21,442 INFO    MainThread:2042 [wandb_run.py:_redirect():2097] Redirects installed.
2024-01-30 16:09:21,443 INFO    MainThread:2042 [wandb_init.py:init():830] run started, returning control to user process
2024-01-30 16:09:21,445 INFO    MainThread:2042 [wandb_run.py:_config_callback():1281] config_cb None None {'configs': './configs/classifier_ellipse.cfg', 'mode': 'train', 'task': 'branin', 'seed': 123, 'condition': 1.0, 'lamda': 0.0, 'temp': '90', 'suffix': '', 'name': 'new_classifier_ellipse_128', 'score_matching': True, 'epochs': 1000, 'max_steps': 'None', 'train_time': 'None', 'num_workers': 8, 'checkpoint_every_n_epochs': 50, 'checkpoint_every_n_steps': 'None', 'checkpoint_time_interval': 'None', 'val_frac': 0.1, 'use_gpu': True, 'simple_clip': False, 'which_gpu': 3, 'normalise_x': True, 'normalise_y': True, 'dataset': 'mnist', 'dataroot': '~/.datasets', 'saveroot': '~/.saved', 'expname': 'default', 'num_steps': 1000, 'T0': 1.0, 'vtype': 'gaussian', 'batch_size': 128, 'test_batch_size': 256, 'num_iterations': 10000, 'gamma': 2.0, 'real': True, 'debias': False, 'learning_rate': 0.001, 'auto_tune_lr': False, 'hidden_size': 1024, 'depth': 'None', 'dropout_p': 0.15, 'beta_min': 0.01, 'beta_max': 2.0}
2024-01-30 16:44:26,670 WARNING MsgRouterThr:2042 [router.py:message_loop():77] message_loop has been closed
