Traceback (most recent call last):
  File "design_baselines/diff_multi/DKL_train_regression_x0_multi.py", line 713, in <module>
    device=device,
  File "design_baselines/diff_multi/DKL_train_regression_x0_multi.py", line 358, in run_classifier
    temp=args.temp)
  File "design_baselines/diff_multi/DKL_train_regression_x0_multi.py", line 254, in get_loaders
    train_dataset, val_dataset = split_dataset(task, val_frac, device, temp)
  File "design_baselines/diff_multi/DKL_train_regression_x0_multi.py", line 214, in split_dataset
    w = get_weights(y[:,0:1], temp=temp) + get_weights(y[:,1:2], temp=temp) - get_weights(y[:,2:3], temp=temp)
  File "/mnt/284ac980-b350-4035-8e02-707f671ad89e/wmu30/ddom-multi-gui/design_baselines/diff_multi/util.py", line 132, in get_weights
    scores_np = scores[:, 0]
IndexError: index 0 is out of bounds for axis 1 with size 0
('out_directory: '
 './experiments/compound/multi_DKL/1469983670/wandb/run-20231123_002749-isnhush6/files')
The device used is : cuda
[0.00069499 0.00182616 0.00270885 0.00360384 0.00472049 0.00615482
 0.00799262 0.01046068 0.01373796 0.01794526 0.02333119 0.03014906
 0.03895919 0.0510018  0.06701496 0.0879034  0.11487776 0.14924302
 0.18857277 0.17910107]